/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChainsNewRouteImport } from './routes/chains/new'
import { Route as ChainsChainIdRouteImport } from './routes/chains/$chainId'
import { Route as ApiChainsIndexRouteImport } from './routes/api/chains/index'
import { Route as ApiChainsShareKeyIndexRouteImport } from './routes/api/chains/$shareKey/index'
import { Route as ApiChainsShareKeyVoteIndexRouteImport } from './routes/api/chains/$shareKey/vote/index'
import { Route as ApiChainsShareKeyResultsIndexRouteImport } from './routes/api/chains/$shareKey/results/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsNewRoute = ChainsNewRouteImport.update({
  id: '/chains/new',
  path: '/chains/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsChainIdRoute = ChainsChainIdRouteImport.update({
  id: '/chains/$chainId',
  path: '/chains/$chainId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChainsIndexRoute = ApiChainsIndexRouteImport.update({
  id: '/api/chains/',
  path: '/api/chains/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChainsShareKeyIndexRoute = ApiChainsShareKeyIndexRouteImport.update({
  id: '/api/chains/$shareKey/',
  path: '/api/chains/$shareKey/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChainsShareKeyVoteIndexRoute =
  ApiChainsShareKeyVoteIndexRouteImport.update({
    id: '/api/chains/$shareKey/vote/',
    path: '/api/chains/$shareKey/vote/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChainsShareKeyResultsIndexRoute =
  ApiChainsShareKeyResultsIndexRouteImport.update({
    id: '/api/chains/$shareKey/results/',
    path: '/api/chains/$shareKey/results/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
  '/chains/new': typeof ChainsNewRoute
  '/api/chains/': typeof ApiChainsIndexRoute
  '/api/chains/$shareKey/': typeof ApiChainsShareKeyIndexRoute
  '/api/chains/$shareKey/results/': typeof ApiChainsShareKeyResultsIndexRoute
  '/api/chains/$shareKey/vote/': typeof ApiChainsShareKeyVoteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
  '/chains/new': typeof ChainsNewRoute
  '/api/chains': typeof ApiChainsIndexRoute
  '/api/chains/$shareKey': typeof ApiChainsShareKeyIndexRoute
  '/api/chains/$shareKey/results': typeof ApiChainsShareKeyResultsIndexRoute
  '/api/chains/$shareKey/vote': typeof ApiChainsShareKeyVoteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
  '/chains/new': typeof ChainsNewRoute
  '/api/chains/': typeof ApiChainsIndexRoute
  '/api/chains/$shareKey/': typeof ApiChainsShareKeyIndexRoute
  '/api/chains/$shareKey/results/': typeof ApiChainsShareKeyResultsIndexRoute
  '/api/chains/$shareKey/vote/': typeof ApiChainsShareKeyVoteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chains/$chainId'
    | '/chains/new'
    | '/api/chains/'
    | '/api/chains/$shareKey/'
    | '/api/chains/$shareKey/results/'
    | '/api/chains/$shareKey/vote/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chains/$chainId'
    | '/chains/new'
    | '/api/chains'
    | '/api/chains/$shareKey'
    | '/api/chains/$shareKey/results'
    | '/api/chains/$shareKey/vote'
  id:
    | '__root__'
    | '/'
    | '/chains/$chainId'
    | '/chains/new'
    | '/api/chains/'
    | '/api/chains/$shareKey/'
    | '/api/chains/$shareKey/results/'
    | '/api/chains/$shareKey/vote/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChainsChainIdRoute: typeof ChainsChainIdRoute
  ChainsNewRoute: typeof ChainsNewRoute
  ApiChainsIndexRoute: typeof ApiChainsIndexRoute
  ApiChainsShareKeyIndexRoute: typeof ApiChainsShareKeyIndexRoute
  ApiChainsShareKeyResultsIndexRoute: typeof ApiChainsShareKeyResultsIndexRoute
  ApiChainsShareKeyVoteIndexRoute: typeof ApiChainsShareKeyVoteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains/new': {
      id: '/chains/new'
      path: '/chains/new'
      fullPath: '/chains/new'
      preLoaderRoute: typeof ChainsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains/$chainId': {
      id: '/chains/$chainId'
      path: '/chains/$chainId'
      fullPath: '/chains/$chainId'
      preLoaderRoute: typeof ChainsChainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/': {
      id: '/api/chains/'
      path: '/api/chains'
      fullPath: '/api/chains/'
      preLoaderRoute: typeof ApiChainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/$shareKey/': {
      id: '/api/chains/$shareKey/'
      path: '/api/chains/$shareKey'
      fullPath: '/api/chains/$shareKey/'
      preLoaderRoute: typeof ApiChainsShareKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/$shareKey/vote/': {
      id: '/api/chains/$shareKey/vote/'
      path: '/api/chains/$shareKey/vote'
      fullPath: '/api/chains/$shareKey/vote/'
      preLoaderRoute: typeof ApiChainsShareKeyVoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/$shareKey/results/': {
      id: '/api/chains/$shareKey/results/'
      path: '/api/chains/$shareKey/results'
      fullPath: '/api/chains/$shareKey/results/'
      preLoaderRoute: typeof ApiChainsShareKeyResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChainsChainIdRoute: ChainsChainIdRoute,
  ChainsNewRoute: ChainsNewRoute,
  ApiChainsIndexRoute: ApiChainsIndexRoute,
  ApiChainsShareKeyIndexRoute: ApiChainsShareKeyIndexRoute,
  ApiChainsShareKeyResultsIndexRoute: ApiChainsShareKeyResultsIndexRoute,
  ApiChainsShareKeyVoteIndexRoute: ApiChainsShareKeyVoteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
